{
  "formatVersion": "1.1",
  "component": {
    "group": "org.wgpu4j",
    "module": "wgpu4j",
    "version": "69.69.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        }
      ],
      "files": [
        {
          "name": "wgpu4j-69.69.69.jar",
          "url": "wgpu4j-69.69.69.jar",
          "size": 29225147,
          "sha512": "b0befadcf57b730acdfeb77ecef3d84a6af84f853ac6d893b2d318097ff6ecb2b165345739d3018ff8f59f403266f1545d30dab505119aaf52ccaaa17314a92b",
          "sha256": "e8e05649310ab4855488491d2f51fa34c4aa2e19cb788afe7f43e784bab118f2",
          "sha1": "f2b69894b202f0153dc93c9af2086e56f520c865",
          "md5": "5f70d9a1586e742236440e1604f12322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        }
      ],
      "files": [
        {
          "name": "wgpu4j-69.69.69.jar",
          "url": "wgpu4j-69.69.69.jar",
          "size": 29225147,
          "sha512": "b0befadcf57b730acdfeb77ecef3d84a6af84f853ac6d893b2d318097ff6ecb2b165345739d3018ff8f59f403266f1545d30dab505119aaf52ccaaa17314a92b",
          "sha256": "e8e05649310ab4855488491d2f51fa34c4aa2e19cb788afe7f43e784bab118f2",
          "sha1": "f2b69894b202f0153dc93c9af2086e56f520c865",
          "md5": "5f70d9a1586e742236440e1604f12322"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wgpu4j-69.69.69-sources.jar",
          "url": "wgpu4j-69.69.69-sources.jar",
          "size": 27912421,
          "sha512": "3cfd3e5fdd84f1191baec31d41fb97c4a29817121415a1a1f1349f27aac356d751f216ff1e6b892b279ed78a7b8db799c6f3a1536931df70d260df149a2cb57c",
          "sha256": "6b46ae49cb880af6773b56c2b66fa335ead319c26c1106170b1f4aff7d66ce4b",
          "sha1": "47b03b1fe27599afa0c31f6db74262d1eb78ca9c",
          "md5": "bc7297410aba7e605cd6d9afa98bc183"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wgpu4j-69.69.69-javadoc.jar",
          "url": "wgpu4j-69.69.69-javadoc.jar",
          "size": 2865844,
          "sha512": "cf46151d665b9e09d7ee4599caedda7883b2d75f32d94864a039cb791f6fe45ce9132eb0499f8ec6688e986319003ce88427c4f1c21be26004f9a30bbccf5549",
          "sha256": "9500d58f3daf0d09f2028fd0b49681142fedd701cfd946bbb85b4898493926ee",
          "sha1": "7ccaabe08f2312339e9efd3b0f4e733996e79bd1",
          "md5": "0c0323157adba9939561e67919540dae"
        }
      ]
    }
  ]
}
