{
  "formatVersion": "1.1",
  "component": {
    "group": "org.wgpu4j",
    "module": "wgpu4j",
    "version": "29.0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        }
      ],
      "files": [
        {
          "name": "wgpu4j-29.0.1.1.jar",
          "url": "wgpu4j-29.0.1.1.jar",
          "size": 29232191,
          "sha512": "4dff371db1e0a88a230ee39d255637bf53d586cdf8fedfb5954e455c033ad4e1088bde3cf39399829381d78d1ffbcb3f2faaf08566a94a2edaa1f2d052cd0713",
          "sha256": "5fed13ec08be4383321ad6052b956f195fed3c376429d4f6593322c08d6f70a8",
          "sha1": "a05a5372f891b4d71fe9e730adcb604434f4de28",
          "md5": "258bad3fb4fa968496d5586900709614"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        }
      ],
      "files": [
        {
          "name": "wgpu4j-29.0.1.1.jar",
          "url": "wgpu4j-29.0.1.1.jar",
          "size": 29232191,
          "sha512": "4dff371db1e0a88a230ee39d255637bf53d586cdf8fedfb5954e455c033ad4e1088bde3cf39399829381d78d1ffbcb3f2faaf08566a94a2edaa1f2d052cd0713",
          "sha256": "5fed13ec08be4383321ad6052b956f195fed3c376429d4f6593322c08d6f70a8",
          "sha1": "a05a5372f891b4d71fe9e730adcb604434f4de28",
          "md5": "258bad3fb4fa968496d5586900709614"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wgpu4j-29.0.1.1-sources.jar",
          "url": "wgpu4j-29.0.1.1-sources.jar",
          "size": 27914443,
          "sha512": "e68fec09a4ec4a1655c2717233e5e38983044cea5107789f7c987908dbae6c2b7e22be13cc45c92bbf2dc7c71be5f10aaeb0fb352e9772fbfc4c25b77f842c18",
          "sha256": "4a1b2335b0ab8977f249f5191e8f5b426031f98a0e4a4f3cddd2426f054ed79e",
          "sha1": "3ba85adf7a521df1ddb79ffaa20a80383643c743",
          "md5": "b3f1862aca62fc0e10d2fb3d18128265"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wgpu4j-29.0.1.1-javadoc.jar",
          "url": "wgpu4j-29.0.1.1-javadoc.jar",
          "size": 2881072,
          "sha512": "b68b2fdcebb6a23f1db6aff20242978bf40461c1a70b7b8c2d21b5a2ee59f6b6f34d4b56acbd57ec6877880884dd39ea0a0e08cd2c9e8f02a69b32d333a9c795",
          "sha256": "150864b9064bb12d426b76859e4368c6847cc2e55e0dcd4eb9d02c4491659cc4",
          "sha1": "3ad174290d20e7585a9f4bbdc8ab622bf10e593b",
          "md5": "f138b98f47c2dae8e5387c654576c8f9"
        }
      ]
    }
  ]
}
